import React, { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { CheckIcon } from 'lucide-react';
import { Container, Section } from '../Layout';
import { SectionHeading } from '../SectionHeading';
import { ButtonLink } from '../Button';
import { BotanicalMotif } from '../Ornament';
import { journeyInterests } from '../../data/homepage';

export function JourneySection() {
  const [selected, setSelected] = useState<string[]>(['tea', 'table']);

  const toggle = (id: string) =>
  setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);

  const chosen = journeyInterests.filter((interest) => selected.includes(interest.id));

  return (
    <Section surface="forestDeep" id="journey" className="overflow-hidden">
      <BotanicalMotif className="pointer-events-none absolute -left-16 bottom-10 hidden h-80 w-96 text-ivory/[0.05] lg:block" />

      <Container className="relative">
        <div className="grid gap-14 lg:grid-cols-12 lg:gap-16">
          <div className="lg:col-span-5">
            <SectionHeading
              eyebrow="Plan Your Stay"
              title={
              <>
                  Your Estate
                  <br /> Journey
                </>
              }
              lede="No two parties want the same days. Tell us what draws you, and the house is arranged around it before you arrive."
              tone="dark"
              ornament="diamond" />
            

            <p className="mt-9 max-w-prose text-[15px] leading-relaxed text-ivory/70">
              Choose the threads that interest you. We will return a proposed rhythm for each day — walks, tastings,
              meals and quiet hours — written by the people who keep the house, not generated by a booking engine.
            </p>

            <div className="mt-10 flex flex-wrap gap-3" role="group" aria-label="Interests for your stay">
              {journeyInterests.map((interest) => {
                const isOn = selected.includes(interest.id);
                return (
                  <button
                    key={interest.id}
                    type="button"
                    aria-pressed={isOn}
                    onClick={() => toggle(interest.id)}
                    className={`inline-flex items-center gap-2.5 border px-4 py-2.5 font-sans text-[10px] font-semibold uppercase tracking-eyebrow transition-colors duration-200 ease-estate ${
                    isOn ?
                    'border-gold bg-gold/15 text-gold-light' :
                    'border-ivory/25 text-ivory/70 hover:border-ivory/50 hover:text-ivory'}`
                    }>
                    
                    {isOn ? <CheckIcon className="h-3 w-3" strokeWidth={2} aria-hidden="true" /> : null}
                    {interest.label}
                  </button>);

              })}
            </div>

            <ButtonLink
              href="#enquire"
              variant="gold"
              size="lg"
              className="mt-11 border-gold/70 text-gold-light hover:bg-gold/15">
              
              Build Your Stay
            </ButtonLink>
          </div>

          <div className="lg:col-span-7">
            <div className="border border-ivory/15 p-8 sm:p-11">
              <div className="flex items-baseline justify-between gap-6 border-b border-ivory/15 pb-6">
                <h3 className="font-serif text-2xl text-ivory">A day shaped to your interests</h3>
                <p className="u-eyebrow shrink-0 text-[9px] text-gold">
                  {chosen.length} {chosen.length === 1 ? 'thread' : 'threads'}
                </p>
              </div>

              <div className="min-h-[18rem]">
                <AnimatePresence initial={false} mode="popLayout">
                  {chosen.length ?
                  chosen.map((interest, position) =>
                  <motion.div
                    key={interest.id}
                    layout
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.22, delay: position * 0.04, ease: [0.23, 1, 0.32, 1] }}
                    className="flex gap-6 border-b border-ivory/10 py-7 last:border-b-0">
                    
                        <span className="u-eyebrow w-14 shrink-0 pt-1.5 text-[9px] text-gold/70">
                          {String(position + 1).padStart(2, '0')}
                        </span>
                        <div>
                          <p className="u-eyebrow text-[9px] text-ivory/50">{interest.label}</p>
                          <p className="mt-3 font-serif text-xl italic text-gold-light">{interest.moment}</p>
                          <p className="mt-3 text-[15px] leading-relaxed text-ivory/70">{interest.detail}</p>
                        </div>
                      </motion.div>
                  ) :

                  <motion.p
                    key="empty"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.2, ease: [0.23, 1, 0.32, 1] }}
                    className="py-16 text-center font-serif text-lg italic text-ivory/50">
                    
                      Choose a thread or two, and the day begins to take shape.
                    </motion.p>
                  }
                </AnimatePresence>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </Section>);

}